# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb28aef8890f70263cb62aa07a21a44067869b705d4fd7305266760f81b12e46f192a26c6cf7cf2b8ff63c6d442c2fe386d7151448b6c429d5b41026b4e4108c

test:
  secret_key_base: dff67ee8c37ebdaed07386f05e6153eb424664b3c84d231651da815737d004eada0155d0b2e1dbf0d0a26e8c58aed80be2c37880a86a50ccaca60d2f03a94055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
